server.port: 8081

spring.jackson:
  date-format: com.fasterxml.jackson.databind.util.StdDateFormat
  time-zone: Asia/Tokyo
  property-naming-strategy: SNAKE_CASE

resource-server.uri: http://localhost:8090

web-client:
  connect-timeout: 500
  read-timeout: 500
  write-timeout: 500

# Resource Server Config
spring.security.oauth2.resourceserver.jwt:
  issuer-uri: http://localhost:9000/auth/realms/todo-api

# Logging
logging:
  level:
    com.example: debug
    org.springframework:
      security: trace
      web:
        client:
          RestTemplate: debug
        reactive:
          function:
            client:
              WebClient: debug
