server.port: 8090

spring.jackson:
  date-format: com.fasterxml.jackson.databind.util.StdDateFormat
  time-zone: Asia/Tokyo
  property-naming-strategy: SNAKE_CASE

spring.datasource.sql-script-encoding: utf-8

spring.security.oauth2.resourceserver.opaquetoken:
  client-id: todo-resource-server
  client-secret: 68329342-efc9-4223-ad8d-6642d47fac15
  introspection-uri: http://localhost:9000/auth/realms/todo-api/protocol/openid-connect/token/introspect

logging:
  level:
    com.example: debug
    org.springframework:
      jdbc.core.JdbcTemplate: debug
      security: trace
      web:
        client:
          RestTemplate: debug
        reactive:
          function:
            client:
              WebClient: debug
